---
- hosts: apache
  sudo: yes
  tasks:
    - name: install apache
      apt: name=apache update_cache=yes state=latest

    - name: enabled mod_rewrite
      apache_module: name=rewrite state=present
      notify:
        - restart apache

    - name: apache listen on port 8081
      lineinfile: dest=/etc/apache/ports.conf regexp="^Listen 80" line="Listen 8081" state=present
      notify:
        - restart apache

    - name: apache virtualhost on port 8081
      lineinfile: dest=/etc/apache/sites-available/000-default.conf regexp="^<VirtualHost \*:80>" line="<VirtualHost *:8081>" state=present
      notify:
        - restart apache

  handlers:
    - name: restart apache
      service: name=apache state=restarted